// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	enumerator "go.bug.st/serial/enumerator"
)

// enumeratePortsInterface is an autogenerated mock type for the enumeratePortsInterface type
type enumeratePortsInterface struct {
	mock.Mock
}

// GetDetailedPortsList provides a mock function with given fields:
func (_m *enumeratePortsInterface) GetDetailedPortsList() ([]*enumerator.PortDetails, error) {
	ret := _m.Called()

	var r0 []*enumerator.PortDetails
	if rf, ok := ret.Get(0).(func() []*enumerator.PortDetails); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*enumerator.PortDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
