// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	serial "go.bug.st/serial"
)

// openComPortInterface is an autogenerated mock type for the openComPortInterface type
type openComPortInterface struct {
	mock.Mock
}

// Open provides a mock function with given fields: portName, mode
func (_m *openComPortInterface) Open(portName string, mode *serial.Mode) (serial.Port, error) {
	ret := _m.Called(portName, mode)

	var r0 serial.Port
	if rf, ok := ret.Get(0).(func(string, *serial.Mode) serial.Port); ok {
		r0 = rf(portName, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(serial.Port)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *serial.Mode) error); ok {
		r1 = rf(portName, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
